const express = require('express');
const router = express.Router();
const { getProfile, updateProfile, changePassword, getDashboard, getReferralInfo } = require('../controllers/userController');
const { protect } = require('../middleware/auth');
router.get('/profile', protect, getProfile);
router.put('/profile', protect, updateProfile);
router.put('/password', protect, changePassword);
router.get('/dashboard', protect, getDashboard);
router.get('/referral', protect, getReferralInfo);
module.exports = router;
